# Make.PHONY: all
CLASS = \
Main.class \
Edges.class \
Shortest.class \
Vehicle.class \
Random_set.class \
Oder.class \
FCFS.class

all: Main

Main: Main.java
	javac Main.java

.PHONY: clean
clean:
	rm -rf $(CLASS)
